import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import DarkVeil from "@/components/DarkVeil";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","500","800"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative w-full h-screen">
              <div className="absolute inset-0 z-0">
                <DarkVeil hueShift={340} />
              </div>
              <div className="relative z-10">
                {children}
              </div>
            </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
